# Generated by Django 5.1 on 2024-08-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.BigIntegerField(verbose_name='telefone'),
        ),
    ]
